sites:
  example:
    name: Example Site
    url_pattern: https://example.com
    selectors:
      title: h1
      content: main
    extract:
    - type: text
      selector: h1
      name: title
    - type: text
      selector: main
      name: content
    wait_for: h1
  finance:
    name: finance
    description: Extract stock information
    url_pattern: https://www.google.com/finance
    selectors:
      stock_price:
        css: .YMlKec.fxKbKc
        description: Current stock price
        multiple: false
      price_change:
        css: .P2Luy.Ez2Ioe
        description: Price change
        multiple: false
      company_name:
        css: .zzDege
        description: Company name
        multiple: false
      market_cap:
        css: '[data-metric="MARKET_CAP"] .P6K39c'
        description: Market capitalization
        multiple: false
      volume:
        css: '[data-metric="VOLUME"] .P6K39c'
        description: Trading volume
        multiple: false
      news_items:
        css: .yY3Lee
        description: News articles
        multiple: true
      search_input:
        css: .Ax4B8.ZAGvjd
        description: Search input field
        multiple: false
  magentasport_basketball:
    name: Magenta Sport Basketball
    description: Extract basketball games from Magenta Sport
    url_pattern: https://www.magentasport.de/basketball
    selectors:
      game_container:
        css: div.game-container
        description: Container for each game
        multiple: true
      teams:
        css: .teams
        description: Teams playing
        multiple: false
      date:
        css: .date
        description: Game date
        multiple: false
      time:
        css: .time
        description: Game time
        multiple: false
      location:
        css: .location
        description: Game location
        multiple: false
    extract:
    - type: text
      selector: .teams
      name: teams
    - type: text
      selector: .date
      name: date
    - type: text
      selector: .time
      name: time
    - type: text
      selector: .location
      name: location
    wait_for: div.game-container
output_dir: output
browser:
  headless: true
  viewport:
    width: 1280
    height: 720
  timeout: 30000
templates_dir: templates
default_template:
  selectors:
    title: h1
    content: main
  wait_for: h1
  extract:
  - type: text
    selector: h1
    name: title
  - type: text
    selector: main
    name: content
logging:
  level: info
  file: auto-browser.log
